# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594c37d9bf286952835103716000fb53670f85d1aac9c41819c48c36cf378cd67fd6a8590c2858a005a57a4ff32760b1faf01f7b21c01ed7c3db1d5871c68eae

test:
  secret_key_base: 25410419d7cd2b4b741e0051d2427539719b8239d0f26df7a59c79285d89ad9100f909e0896b32cb12695b891f68c86467f2aafd5372454620528af71eb9e79b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
